services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    container_name: fonbet_postgres
    environment:
      POSTGRES_DB: fonbet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always

volumes:
  postgres_data:
